(lang dune 3.21)
(name kairos)
(generate_opam_files false)
(using menhir 2.1)
(using rocq 0.11)
(package
 (name kairos))
(package
 (name kairos-cli))
(package
 (name kairos-lsp))
(package
 (name kairos-engine-runtime))
(package
 (name kairos-automata-contract))
(package
 (name kairos-spot-adapter))
(package
 (name kairos-proof-contract))
(package
 (name kairos-telemetry))
(package
 (name kairos-why3-adapter))
