(*---------------------------------------------------------------------------
 * Kairos - deductive verification for synchronous programs
 * Copyright (C) 2026 Frederic Dabrowski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *---------------------------------------------------------------------------*)

(** Observer elaboration helpers.

    Observers are proof-only variables generated by the front-end. This module
    only builds their declarations and transition updates; validity checks live
    in [Validation].
*)

val observer_raw_vdecl : Surface.Ast.observer_decl -> Surface.Syntax.raw_vdecl
(** Turn an observer declaration into the proof-only variable that stores its
    value. *)

type schedule
(** Dependency-respecting execution orders for observer initialization and
    ordinary steps. *)

val schedule :
  predicates:Surface.Ast.predicate_decl list ->
  Surface.Ast.observer_decl list ->
  schedule
(** Compute stable topological orders from direct references and references
    captured by predicates; reject instantaneous dependency cycles. *)

val observer_updates_for_transition :
  init_state:string ->
  schedule ->
  Surface.Ast.transition ->
  Surface.Ast.stmt list
(** Select and order observer updates for a transition: initialization updates
    when leaving the initial state, step updates otherwise. *)

val observer_locals : Surface.Ast.observer_decl list -> Surface.Syntax.raw_vdecl list
(** Generate the proof-only local declarations associated with observers. *)
