(include_subdirs unqualified)

(library
 (name kr_domain_core)
 (wrapped true)
 (private_modules
  core_fo_simplifier_keys
  core_fo_simplifier_bool
  kr_domain_core_history_analysis
  kr_domain_core_history_layout
  kr_domain_core_history_lowering)
 (libraries yojson)
 (preprocess
  (pps ppx_deriving.show ppx_deriving_yojson)))
