(menhir
 (modules parser)
 (flags --table --inspection))

(library
 (name kairos_lang_parse)
 (public_name kairos.internal.input_lang.parse)
 (wrapped true)
 (private_modules (:standard \ parse))
 (libraries kairos_lang_shared kairos_lang_core kairos_lang_surface kairos_lang_elaborate menhirLib sedlex yojson)
 (flags (:standard -open Kairos_lang_shared -open Kairos_lang_core -open Kairos_lang_surface -open Kairos_lang_elaborate))
 (preprocess
  (pps sedlex.ppx ppx_deriving_yojson)))
