(library
 (name kairos_domain_verification)
 (public_name kairos.domain_verification)
 (wrapped false)
 (modules
  ir_shared_types
  ir
  ir_formula
  ir_transition
  automaton_types
  product_types
  temporal_automata
  product_build
  fo_time
  fo_contradiction
  fo_current_input
  product_characteristics
  ir_fact_family_metrics
  from_model
  pre
  product_reachability
  post
  formula_canonical
  contract_formula_index
  contract_partition
  automata_preparation
  temporal_lower
  step_contract_projection
  proof_plan
  orchestration)
 (libraries kairos_domain_core))
