(library
 (name kairos_domain_verification)
 (public_name kairos.domain_verification)
 (wrapped false)
 (modules
  ir_shared_types
  ir
  ir_formula
  ir_transition
  automaton_types
  product_types
  temporal_automata
  product_build
  fo_time
  fo_contradiction
  fo_current_input
  obligation_family_projection
  product_characteristics
  product_summary_projection
  kernel_clause_projection_formula
  kernel_clause_projection_transition_id
  kernel_clause_projection
  canonical_obligations
  ir_fact_family_metrics
  from_model
  pre
  product_reachability
  post
  formula_canonical
  contract_formula_index
  contract_partition
  automata_preparation
  temporal_lower
  step_contract_projection
  proof_plan
  orchestration)
 (private_modules
  kernel_clause_projection_formula
  kernel_clause_projection_transition_id)
 (libraries kairos_domain_core))
