(*---------------------------------------------------------------------------
 * Kairos - deductive verification for synchronous programs
 * Copyright (C) 2026 Frédéric Dabrowski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *---------------------------------------------------------------------------*)


(** Canonical IR types used between middle-end passes and backends.

    This module defines:
    - logical formulas with metadata;
    - product/summaries structures used by local-proof generation;
    - node/program IR containers consumed by later pipeline phases. *)

open Ir_shared_types
open Core_syntax

(** Metadata attached to one logical formula in the IR. *)
type formula_meta = {
  oid : formula_id;
  loc : Loc.loc option;
  family : string option;
}

(** Formula used in IR summaries and goals. *)
type 'phase summary_formula = {
  logic : 'phase Core_syntax.hexpr;
  meta : formula_meta;
}

(** Materialized temporal history layout used after canonical IR construction. *)
type temporal_layout = Pre_k_layout.pre_k_info list

(** Product state with raw indices into the deterministic partial assumption
    and guarantee monitors. *)
type product_state = {
  prog_state : ident;
  assume_state_index : automaton_state_index;
  guarantee_state_index : automaton_state_index;
}

(** Raw assumption/guarantee monitor indices at one product position.

    The program control state is deliberately absent: a summary derives it
    from its unique executable transition. *)
type monitor_state_pair = {
  assume_state_index : automaton_state_index;
  guarantee_state_index : automaton_state_index;
}

(** Normalized executable transition used by the IR summaries. *)
type transition = {
  src_state : ident;
  dst_state : ident;
  guard_expr : expr option;
  body_stmts : stmt list;
}


(** One guarantee successor of a program–assumption prefix. *)
type 'phase product_case = {
  (** The program and assumption destinations are derived from the containing
      summary. Only the varying guarantee destination is stored here. *)
  guarantee_destination_state_index : automaton_state_index;
  guarantee_guard : 'phase summary_formula;
}

(** Traceability metadata for one local summary. *)
type product_step_summary_trace = { step_uid : transition_index }

(** Grouping key for one local product-step summary. *)
type 'phase product_step_summary_identity = {
  program_step : transition;
  (** Source states of the two monitors. The program source is
      [program_step.src_state]. *)
  monitor_source : monitor_state_pair;
  (** Assumption-monitor successor fixed by this summary. *)
  assume_destination_state_index : automaton_state_index;
  assume_guard : 'phase Core_syntax.hexpr;
}

(** Local summary of grouped product steps. *)
type 'phase product_step_summary = {
  trace : product_step_summary_trace;
  identity : 'phase product_step_summary_identity;
  propagation_requires : 'phase summary_formula list;
  requires : 'phase summary_formula list;
  ensures : 'phase summary_formula list;
  elaboration_checks : 'phase summary_formula list;
  (** Outgoing guarantee-monitor cases.

      Their guard disjunction is the progress condition. An empty list denotes
      total blocking; conditional blocking appears as incomplete guard
      coverage even when cases exist. *)
  product_cases : 'phase product_case list;
}

val product_source : 'phase product_step_summary -> product_state
(** Derive the complete source product state from the summary identity. *)

val product_destination :
  'phase product_step_summary ->
  'phase product_case ->
  product_state
(** Derive one complete destination product state from its containing
    summary and guarantee case. *)

(** [ensures] is the Rocq-facing structural postcondition set.
    [elaboration_checks] contains proof checks generated by frontend
    desugaring. *)

(** Core node signature required by the canonical IR. *)
type node_signature = {
  sem_nname : ident;
  sem_type_decls : enum_decl list;
  sem_function_decls : pure_function_decl list;
  sem_methods : method_decl list;
  sem_inputs : vdecl list;
  sem_outputs : vdecl list;
  sem_locals : vdecl list;
  sem_states : ident list;
  sem_init_state : ident;
}

(** State invariant already converted to FO (non-temporal by construction). *)
type state_invariant = {
  state : ident;
  formula : Core_syntax.historical Core_syntax.hexpr;
}

(** Source-level specs and invariants kept for traceability/export. *)
type source_info = {
  assumes : ltl list;
  guarantees : ltl list;
  state_invariants : state_invariant list;
}

(** Full canonical IR for one node. *)
type 'phase node_ir = {
  semantics : node_signature;
  source_info : source_info;
  temporal_layout : temporal_layout;
  summaries : 'phase product_step_summary list;
}

(** Canonical IR for a whole program. *)
type program_ir = { nodes : Core_syntax.history_free node_ir list }
