(*---------------------------------------------------------------------------
 * Kairos - deductive verification for synchronous programs
 * Copyright (C) 2026 Frédéric Dabrowski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *---------------------------------------------------------------------------*)

(** Compilation of the imperative body of the [step] function.

    Translates the state machine of a Kairos node into imperative WhyML
    expressions: assignment sequences, transition guards and a pattern match
    on the current control state. Produces the body of the [step] function
    and the [step_from_<state>] helper functions generated by {!Why_compile}. *)

(** [compile_seq env asserts actions] compiles a sequence of imperative actions
    into a WhyML expression. [asserts] is the list of assertions to prepend
    to the block (from invariants or entry contracts). *)
val compile_seq :
  Why_compile_expr.env ->
  Why3.Ptree.term list ->
  Why_runtime_view.runtime_action_view list ->
  Why3.Ptree.expr

(** [compile_transition_body env asserts t] compiles the body of transition [t]
    into a WhyML expression, prepending [asserts] at the entry point. *)
val compile_transition_body :
  Why_compile_expr.env ->
  Why3.Ptree.term list ->
  Why_runtime_view.runtime_transition_view ->
  Why3.Ptree.expr

(** [compile_state_body env entry_asserts sticky_asserts state transitions]
    compiles the arm for [state] in the pattern match on the current control
    state.

    - [entry_asserts]: per-state assertions inserted at the entry of each
      transition from this state (e.g. the state guard).
    - [sticky_asserts]: persistent assertions inserted in every branch. *)
val compile_state_body :
  Why_compile_expr.env ->
  (Core_syntax.ident * Why3.Ptree.term list) list ->
  (Core_syntax.ident * Why3.Ptree.term list) list ->
  Core_syntax.ident ->
  Why_runtime_view.runtime_transition_view list ->
  Why3.Ptree.expr

(** [compile_transitions env branches] compiles all state branches into a
    WhyML pattern match on the current control state. *)
val compile_transitions :
  Why_compile_expr.env ->
  Why_runtime_view.state_branch_view list ->
  Why3.Ptree.expr

(** [compile_runtime_view env rv] compiles the complete node view into the
    body of the [step] function (pattern match on the current control state). *)
val compile_runtime_view :
  Why_compile_expr.env ->
  Why_runtime_view.t ->
  Why3.Ptree.expr
