(*---------------------------------------------------------------------------
 * Kairos - deductive verification for synchronous programs
 * Copyright (C) 2026 Frédéric Dabrowski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *---------------------------------------------------------------------------*)

(** Generation of Why3 contracts from node clauses.

    Translates Kairos contracts (assumes, guarantees, and transition
    requires/ensures) into the pre/post term lists of the [step] function.
    Each term is annotated with an origin label for UI/VC traceability.
    In relational proof mode, also produces per-step contract information
    for the [step_from_<state>] helper functions generated by {!Why_compile}. *)

(** Contract associated with one product transition in relational mode. *)
type step_contract_info = {
  step : Why_runtime_view.runtime_product_transition_view;
      (** The product transition this contract was derived from. *)
  pre : Why3.Ptree.term list;
      (** Preconditions specific to this step. *)
  post : Why3.Ptree.term list;
      (** Postconditions specific to this step. *)
  forbidden : Why3.Ptree.term list;
      (** Formulas whose violation is intentionally tolerated at this step. *)
}

(** Full contract generation result for a node. *)
type contract_info = {
  pre : Why3.Ptree.term list;
      (** Precondition terms of [step]. *)
  post : Why3.Ptree.term list;
      (** Postcondition terms of [step]. *)
  pre_labels : string list;
      (** Short labels associated with each precondition (for UI display). *)
  post_labels : string list;
      (** Short labels associated with each postcondition. *)
  pre_origin_labels : string list;
      (** Detailed origin labels for precondition traceability. *)
  post_origin_labels : string list;
      (** Detailed origin labels for postcondition traceability. *)
  pre_source_states : string option list;
      (** Source control state for each precondition, when known. *)
  post_source_states : string option list;
      (** Source control state for each postcondition, when known. *)
  post_vcids : string option list;
      (** VC identifier for each postcondition, when present. *)
  step_contracts : step_contract_info list;
      (** Per-step contracts for the product (relational mode only). *)
}

(** [build_contracts ~nodes ~env ~hexpr_needs_old ~runtime ~pure_translation]
    generates the full [step] contract for the node described by [runtime].

    - [~nodes]: list of program nodes, used to resolve cross-node contract
      references.
    - [~env]: compilation environment for the node.
    - [~hexpr_needs_old]: predicate indicating whether a historical expression
      must be wrapped in [old()] in the postcondition.
    - [~pure_translation]: when [true], only transition preconditions are kept
      and the postcondition is left empty (pure translation mode, no
      verification). *)
val build_contracts :
  nodes:Ast.node list ->
  env:Why_compile_expr.env ->
  hexpr_needs_old:(Ast.hexpr -> bool) ->
  runtime:Why_runtime_view.t ->
  pure_translation:bool ->
  contract_info
