(library
 (name kairos_input_lang)
 (public_name kairos.internal.input_lang)
 (wrapped true)
 (private_modules
  (:standard \ kairos_frontend kairos_source_services))
 (libraries kairos_domain_core menhirLib sedlex yojson str)
 (preprocess
  (pps sedlex.ppx ppx_deriving_yojson)))

(menhir
 (modules kx_parse_parser)
 (flags --table --inspection))
