(library
 (name kairos_lang)
 ;  (public_name kairos.internal.input_lang)
 (wrapped true)
 (private_modules
  (:standard \ frontend source_services))
 (libraries kairos_lang_parse kairos_lang_to_model)
 (flags
  (:standard
   -open
   Kairos_lang_parse
   -open
   Kairos_lang_to_model
   -open
   Kairos_lang_shared
   -open
   Kairos_lang_core
   -open
   Kairos_lang_surface))
 (preprocess
  (pps sedlex.ppx ppx_deriving_yojson)))
