(*---------------------------------------------------------------------------
 * Kairos - deductive verification for synchronous programs
 * Copyright (C) 2026 Frederic Dabrowski
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *---------------------------------------------------------------------------*)

(** Observer elaboration helpers.

    Observers are proof-only variables generated by the front-end. This module
    only builds their declarations and transition updates; validity checks live
    in [Kx_elaborate_validation].
*)

val observer_raw_vdecl : Kx_surface_syntax.observer_decl -> Kx_surface_syntax.raw_vdecl

val observer_updates_for_transition :
  init_state:string ->
  Kx_surface_syntax.observer_decl list ->
  Kx_surface_syntax.transition ->
  Kx_surface_syntax.stmt list

val observer_locals : Kx_surface_syntax.observer_decl list -> Kx_surface_syntax.raw_vdecl list
