(documentation
 (package kairos)
 (mld_files
  index
  frontend
  common
  middleend
  artifacts
  backends
  rocq_frontend_boundary
  rocq_proof_scope
  rocq_ocaml_adequacy
  stage1_ocaml_rocq_arbitration
  stage1_phase_facts_audit
  reference_verification_architecture
  temporal_phase_semantics
  product_proof_pipeline_audit
  pipeline_cost_model
  grouped_product_encoding_plan))
