module Abs = Ir

(** Pair raw transitions with their corresponding abstract transitions.
    Both lists originate from the same instrumented node and must be in the
    same order (they are produced by the same [List.map] in the instrumentation
    pass and in [Proof_obligation_raw.build_raw_node]). *)
let zip_transitions (raws : Proof_obligation_ir.raw_transition list)
    (abs_trans : Abs.transition list) :
    (Proof_obligation_ir.raw_transition * Abs.transition) list =
  try List.combine raws abs_trans
  with Invalid_argument _ ->
    failwith
      "Proof_obligation_annotate.annotate: raw transitions and abstract transitions \
       have different lengths — raw_node and abstract node must originate from \
       the same instrumentation pass output"

(** Lift an abstract transition's contracts into an annotated_transition. *)
let annotate_transition (raw : Proof_obligation_ir.raw_transition)
    (abs_t : Abs.transition) : Proof_obligation_ir.annotated_transition =
  { Proof_obligation_ir.raw; requires = abs_t.requires; ensures = abs_t.ensures }

(** Annotate a raw node with Hoare triples.

    The [node] argument is the corresponding IR node: its transitions already
    carry the requires/ensures generated by the abstract post/pre phases. *)
let annotate ~(raw : Proof_obligation_ir.raw_node) ~(node : Abs.node)
    ~(analysis : Product_build.analysis) : Proof_obligation_ir.annotated_node =
  (* [analysis] is kept so the call site can evolve without changing this
     annotation step; the pre/post generation already happened on [node.trans]. *)
  ignore analysis;
  let pairs = zip_transitions raw.transitions node.trans in
  let transitions =
    List.map (fun (r, t) -> annotate_transition r t) pairs
  in
  {
    Proof_obligation_ir.raw;
    transitions;
    coherency_goals    = node.coherency_goals;
    user_invariants    = node.source_info.user_invariants;
  }
