(library
 (name kairos_domain_core)
 (public_name kairos.domain_core)
 (wrapped false)
 (modules
  loc
  core_syntax
  core_syntax_builders
  core_fo_simplifier_keys
  core_fo_simplifier_bool
  core_fo_simplifier
  pretty
  log
  verification_model
  historical_initialization
  pre_k_layout
  pre_k_lowering
  ir
  ir_shared_types
  ir_formula
  ir_transition)
 (private_modules core_fo_simplifier_keys core_fo_simplifier_bool)
 (libraries yojson logs logs.fmt fmt)
 (preprocess
  (pps ppx_deriving.show ppx_deriving_yojson)))
